/* マルチページ版の共通スクリプト：localStorageに集約 */
(()=>{
  const STORAGE_KEY='householdInventoryData.v1';
  const el=s=>document.querySelector(s); const els=s=>Array.from(document.querySelectorAll(s));
  const todayStr=()=>new Date().toISOString().slice(0,10);
  const load=()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw) return {items:[{name:'牛乳',category:'乳製品',reorderPoint:1,unit:'本',note:'',initialStock:0},{name:'卵',category:'乳製品',reorderPoint:1,unit:'パック',note:'',initialStock:0},{name:'洗濯用洗剤',category:'日用品',reorderPoint:1,unit:'個',note:'',initialStock:0}],history:[]}; const d=JSON.parse(raw); d.items??=[]; d.history??=[]; return d;}catch(e){return {items:[],history:[]}}};
  const save=d=>localStorage.setItem(STORAGE_KEY,JSON.stringify(d));
  let state=load();
  const findItemIndex=n=>state.items.findIndex(i=>i.name===n);
  function ensureItemExists(n){let i=findItemIndex(n); if(i===-1){state.items.push({name:n,category:'',reorderPoint:1,unit:'個',note:'',initialStock:0}); i=state.items.length-1; save(state);} return i;}
  function aggregate(){const bought=new Map(), used=new Map(); for(const h of state.history){const m=h.type==='購入'?bought: h.type==='使用'?used:null; if(!m) continue; m.set(h.item,(m.get(h.item)||0)+Number(h.qty||0));}
    return state.items.map(it=>{const b=bought.get(it.name)||0; const u=used.get(it.name)||0; const cur=Number(it.initialStock||0)+b-u; const status= cur<=Number(it.reorderPoint||0)?'⚠ 発注必要':'OK'; return {...it,bought:b,used:u,current:cur,status};});}
  function renderKPI(){ if(el('#kpi-today')) el('#kpi-today').textContent=todayStr(); const rows=aggregate(); if(el('#kpi-items')) el('#kpi-items').textContent=rows.length; if(el('#kpi-zero')) el('#kpi-zero').textContent=rows.filter(r=>r.current===0).length; if(el('#kpi-reorder')) el('#kpi-reorder').textContent=rows.filter(r=>r.current<= (r.reorderPoint||0)).length; }
  function renderDatalist(){ const dl=el('#items-list'); if(!dl) return; dl.innerHTML=state.items.slice().sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(it=>`<option value="${it.name}"></option>`).join('');}
  function renderRecent(){ const tb=el('#recent-input-table tbody'); if(!tb) return; const last=state.history.slice(-20).reverse(); tb.innerHTML=last.map((h,idx)=>`<tr><td>${h.date}</td><td>${h.item}</td><td>${h.type}</td><td>${h.qty}</td><td>${h.note||''}</td><td><button class="btn" data-del="${state.history.length-1-idx}">削除</button></td></tr>`).join(''); tb.querySelectorAll('button[data-del]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.del); state.history.splice(i,1); save(state); renderAll();})); }
  function setupInput(){ const f=el('#purchase-form'); if(!f) return; if(el('#in-date')) el('#in-date').value=todayStr(); f.addEventListener('submit',e=>{ e.preventDefault(); const date=el('#in-date').value||todayStr(); const name=(el('#in-item').value||'').trim(); const type=el('#in-type').value; const qty=Math.max(1, Number(el('#in-qty').value||1)); const note=(el('#in-note').value||'').trim(); if(!name) return; ensureItemExists(name); let merged=false; for(let i=state.history.length-1;i>=0;i--){const h=state.history[i]; if(h.item===name && h.type===type && h.date===date){ h.qty=Number(h.qty||0)+qty; if(note) h.note=note; merged=true; break; }} if(!merged) state.history.push({date,item:name,type,qty,note}); save(state); el('#in-item').value=''; el('#in-qty').value='1'; el('#in-note').value=''; renderAll();}); const add=el('#btn-bulk-add'); if(add) add.addEventListener('click',()=>{ const last=state.history.filter(h=>h.type==='購入').slice(-1)[0]; const name= last?.item || state.items[0]?.name; if(!name) return; ensureItemExists(name); const date=todayStr(); let merged=false; for(let i=state.history.length-1;i>=0;i--){const h=state.history[i]; if(h.item===name && h.type==='購入' && h.date===date){ h.qty=Number(h.qty||0)+1; merged=true; break; }} if(!merged) state.history.push({date,item:name,type:'購入',qty:1,note:'ショートカット'}); save(state); renderAll(); }); }
  function renderInventory(){ const tb=el('#inventory-table tbody'); if(!tb) return; const rows=aggregate(); const q=(el('#inv-search')?.value||'').toLowerCase(); const cat=el('#inv-filter-cat')?.value||''; const filtered=rows.filter(r=>(!q||r.name.toLowerCase().includes(q)) && (!cat||r.category===cat)); tb.innerHTML=filtered.map(r=>`<tr class="${r.current <= (r.reorderPoint||0)?'low':''}"><td>${r.name}</td><td>${r.initialStock||0}</td><td>${r.bought}</td><td>${r.used}</td><td>${r.current}</td><td>${r.reorderPoint||0}</td><td>${r.status}</td><td>${r.category||''}</td></tr>`).join(''); }
  function setupInventoryFilters(){ const sel=el('#inv-filter-cat'); if(!sel) return; const cats=Array.from(new Set(state.items.map(i=>i.category).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'ja')); sel.innerHTML='<option value="">すべてのカテゴリ</option>'+cats.map(c=>`<option value="${c}">${c}</option>`).join(''); const s=el('#inv-search'); if(s) s.addEventListener('input',renderInventory); sel.addEventListener('change',renderInventory); }
  function renderHistory(){ const tb=el('#history-table tbody'); if(!tb) return; tb.innerHTML=state.history.map(h=>`<tr><td>${h.date}</td><td>${h.item}</td><td>${h.type}</td><td>${h.qty}</td><td>${h.note||''}</td></tr>`).join(''); }
  function setupHistoryActions(){ const btn=el('#btn-clear-history'); if(!btn) return; btn.addEventListener('click',()=>{ if(!confirm('履歴を全削除しますか？')) return; state.history=[]; save(state); renderAll(); }); }
  function renderShopping(){ const tb=el('#shopping-table tbody'); if(!tb) return; const rows=aggregate().filter(r=>r.current <= (r.reorderPoint||0)); tb.innerHTML=rows.map(r=>{ const unit= state.items.find(i=>i.name===r.name)?.unit||''; const note= state.items.find(i=>i.name===r.name)?.note||''; const suggest=Math.max(1,(r.reorderPoint||0)-r.current); return `<tr><td>${r.name}</td><td>${r.current}</td><td>${r.reorderPoint||0}</td><td>${unit}</td><td>${note}</td><td>${suggest}</td></tr>`; }).join(''); const area=el('#shopping-text'); if(area){ const text=rows.map(r=>`・${r.name} ${Math.max(1,(r.reorderPoint||0)-r.current)}${state.items.find(i=>i.name===r.name)?.unit||''}`).join('
'); area.value=text||'（発注必要な品目はありません）'; }}
  function renderMaster(){ const tb=el('#master-table tbody'); if(!tb) return; tb.innerHTML=state.items.slice().sort((a,b)=>a.name.localeCompare(b.name,'ja')).map((it,idx)=>`<tr><td>${it.name}</td><td>${it.category||''}</td><td>${it.reorderPoint||0}</td><td>${it.unit||''}</td><td>${it.note||''}</td><td><button class='btn' data-edit='${idx}'>編集</button> <button class='btn danger' data-del='${idx}'>削除</button></td></tr>`).join(''); tb.querySelectorAll('button[data-edit]').forEach(btn=>btn.addEventListener('click',()=>{ const it=state.items[Number(btn.dataset.edit)]; const mi=el('#m-item'); if(mi){ el('#m-item').value=it.name; el('#m-cat').value=it.category||''; el('#m-reorder').value=it.reorderPoint??1; el('#m-unit').value=it.unit||'個'; el('#m-note').value=it.note||''; window.location.href='master.html'; }})); tb.querySelectorAll('button[data-del]').forEach(btn=>btn.addEventListener('click',()=>{ const i=Number(btn.dataset.del); if(!confirm(`「${state.items[i].name}」を削除しますか？
※ 履歴は残ります。`)) return; state.items.splice(i,1); save(state); renderAll(); })); renderDatalist(); setupInventoryFilters(); }
  function setupMasterForm(){ const form=el('#master-form'); if(!form) return; form.addEventListener('submit',e=>{ e.preventDefault(); const name=(el('#m-item').value||'').trim(); if(!name) return; const idx=ensureItemExists(name); state.items[idx].category=(el('#m-cat').value||'').trim(); state.items[idx].reorderPoint=Number(el('#m-reorder').value||0); state.items[idx].unit=(el('#m-unit').value||'個').trim(); state.items[idx].note=(el('#m-note').value||'').trim(); save(state); renderAll(); alert('登録/更新しました'); form.reset(); }); }
  function setupSettings(){ const ex=el('#btn-export'); if(ex) ex.addEventListener('click',()=>{ const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='inventory-backup.json'; a.click(); URL.revokeObjectURL(a.href); }); const im=el('#btn-import'); if(im) im.addEventListener('click',()=> el('#file-import').click()); const fi=el('#file-import'); if(fi) fi.addEventListener('change',async ev=>{ const file=ev.target.files[0]; if(!file) return; const txt=await file.text(); try{ const data=JSON.parse(txt); if(!Array.isArray(data.items)||!Array.isArray(data.history)) throw new Error('フォーマット不正'); state=data; save(state); renderAll(); alert('読み込みました'); }catch(e){ alert('読み込みに失敗しました: '+e.message);} ev.target.value=''; }); const rs=el('#btn-reset'); if(rs) rs.addEventListener('click',()=>{ if(!confirm('初期化します。よろしいですか？')) return; state={items:[],history:[]}; save(state); renderAll(); }); }
  function renderAll(){ renderKPI(); renderInventory(); renderHistory(); renderShopping(); renderMaster(); renderRecent(); }
  function init(){ renderAll(); setupInput(); setupHistoryActions(); setupMasterForm(); setupSettings(); setupInventoryFilters(); }
  document.addEventListener('DOMContentLoaded',init);
})();
